<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>02_Distribución_continua</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-introducción" class="section level1">
<h1>Introducción</h1>
<p>La distribución continua se reconoce por su forma de campana, y resulta ser la distribución continua más importante, ya que mide en forma aproximada muchos fenómenos que ocurren en la naturaleza (Daniel, 2006; Logan, 2010). La curva de distribución, se le llama campana de Gauss o gaussiana es asintótica, simétrica en ambos lados; además, tiene un cambio de cóncavo a convexo.</p>
<p>La curva de distribución normal se puede generar en el entorno de R utilizando los siguientes códigos:</p>
<p><img src="02_Distribuci%C3%B3n_continua_files/figure-html/unnamed-chunk-1-1.png" width="624" /> Figura. 1. Función de densidad normal. El eje x etiqueta la distancia de las desviaciones estándares (sd) respecto a la media (mu=0).</p>
<p>la cual responde a la siguiente ecuación:</p>
<p><span class="math inline">\(f(x)= \frac{1}{\sqrt{2\pi}} e^{^{x^{-2}/2}}\)</span></p>
<p>La función de distribución normal indica que en entre los límites de 1 desviación estándar positiva y 1 desviación estándar negativa, se localiza alrededor del 68% de las observaciones extraídas aleatoriamente de una población distribuída normalmente. El otro 32% estará fuera de estos valores (un 16% por encima de una desviación típica y el otro 16% por debajo). En otras palabras, la probabilidad de que una observación individual escogida al azar sea una descriptora de la población es de un 68% (Fowler, 1999).</p>
<p>La distribución normal está determinada por dos constantes: <span class="math inline">\(\mu = 0\)</span> (media poblacional) y <span class="math inline">\(\sigma = 1\)</span> (desviación estándar poblacional).</p>
<p>Otra forma de generar la curva de distribución normal en R sería:</p>
<p><img src="02_Distribuci%C3%B3n_continua_files/figure-html/unnamed-chunk-3-1.png" width="624" /></p>
<p>En términos generales, se pueden utilizar los siguientes comandos para lograr construir la distribución normal:</p>
<ul>
<li>dnorm()</li>
<li>pnorm()</li>
<li>qnorm()</li>
<li>rnorm()</li>
</ul>
<p>Puede utilizar la ayuda de R para verificar las características de las funciones:</p>
<div class="tutorial-exercise" data-label="explorar_codigo" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="5">
<pre class="text"><code>?dnorm()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>La función dnorm() nos brinda los valores de probabilidad de la función de densidad.</p>
<p>La función pnorm() calcula la probabilidad acumulada, siendo esta el área bajo la curva hasta una ordenada (eje x) específica.</p>
<pre><code>## [1] 0.9772499</code></pre>
<p>Para entender mejor en la forma gráfica proyectamos esta probabilidad.</p>
<p><img src="02_Distribuci%C3%B3n_continua_files/figure-html/unnamed-chunk-5-1.png" width="624" /></p>
<p>El área bajo la curva de la campana de Gauss en color celeste claro representa, que el 97.7% de desviaciones estándares normales son menores a 2 (100%). Bajo el supuesto que el área bajo la curva es 100% de una función de densidad.</p>
<p>La función qnorm(), determina el cuantil de una probabilidad dada.</p>
<pre><code>## [1] 2.000001</code></pre>
<p>El dato representa los valores menores asociados al percentil 97 de la distribución, con una media de cero y desviación estándar de uno.</p>
<p>La función rnorm() genera números aleatorios con distribución normal.</p>
<pre><code>##   [1]  0.58552882  0.70946602 -0.10930331 -0.45349717  0.60588746 -1.81795597
##   [7]  0.63009855 -0.27618411 -0.28415974 -0.91932200 -0.11624781  1.81731204
##  [13]  0.37062786  0.52021646 -0.75053199  0.81689984 -0.88635752 -0.33157759
##  [19]  1.12071265  0.29872370  0.77962192  1.45578508 -0.64432843 -1.55313741
##  [25] -1.59770952  1.80509752 -0.48164736  0.62037980  0.61212349 -0.16231098
##  [31]  0.81187318  2.19683355  2.04919034  1.63244564  0.25427119  0.49118828
##  [37] -0.32408658 -1.66205024  1.76773385  0.02580105  1.12851083 -2.38035806
##  [43] -1.06026555  0.93714054  0.85445172  1.46072940 -1.41309878  0.56740325
##  [49]  0.58318765 -1.30679883 -0.54038607  1.94769266  0.05359027  0.35166284
##  [55] -0.67097654  0.27795369  0.69117127  0.82379533  2.14506502 -2.34694398
##  [61]  0.14959198 -1.34253148  0.55330308  1.58996284 -0.58687959 -1.83237731
##  [67]  0.88813943  1.59348847  0.51685467 -1.29567168  0.05461558 -0.78464937
##  [73] -1.04935282  2.33051196  1.40270538  0.94260085  0.82625829 -0.81154049
##  [79]  0.47624828  1.02125841  0.64538307  1.04314355 -0.30436911  2.47711092
##  [85]  0.97122067  1.86709918  0.67204247 -0.30795338  0.53652372  0.82487007
##  [91] -0.96390148 -0.85508251  1.88694694 -0.39181937 -0.98063295  0.68733210
##  [97] -0.50504352  2.15771982 -0.59979756 -0.69454669</code></pre>
<p>La distribución normal es frecuentemente utilizada para describir la diferencia entre valores observados y valores predichos de un modelo ajustado.</p>
<p>Para entender bien el concepto de áreas baja la curva daremos algunos ejemplos que pueden resolverse con simples funciones de R, siguiendo las reglas básicas de probabilidad.</p>
<div id="section-ejemplos-probabilidad-normal" class="section level2">
<h2>Ejemplos Probabilidad Normal</h2>
<p>Ejemplo 6.1. Determine la probabilidad de z (de la curva normal) con valores que están entre -1.73 y 2.60?</p>
<pre><code>## [1] 0.9535237</code></pre>
<p>R/ el área bajo la curva normal estándar es de 0.95</p>
<p>Ejemplo 6.2. Dada la curva normal estándar, calcular Pr(z mayor igual que 2.65).</p>
<pre><code>## [1] 0.004024589</code></pre>
</div>
<div id="section-casos-para-la-curva-normal-estándar" class="section level2">
<h2>Casos para la curva normal estándar</h2>
<ol style="list-style-type: decimal">
<li><p>Caso 1</p></li>
<li><p>Caso 2</p></li>
<li><p>Caso 3</p></li>
</ol>
<p>PONER FIGURA CASO 3</p>
<ol start="4" style="list-style-type: decimal">
<li>Caso 4</li>
</ol>
<p>PONER FIGURA CASO 4</p>
<ol start="5" style="list-style-type: decimal">
<li>Caso 5</li>
</ol>
<p>PONER FIGURA CASO 5</p>
<ol start="6" style="list-style-type: decimal">
<li>Caso 6</li>
</ol>
</div>
<div id="section-aplicación-de-problemas-con-la-curva-normal-estándar." class="section level2">
<h2>Aplicación de problemas con la curva normal estándar.</h2>
<p>Los parámetros de estimación de la distribución normal son la media y desviación típica . Cualquier observación de x sobre la línea base de la curva normal se puede estandarizar como el número de unidades de desviaciones típicas. La forma de responder a cuestiones de probabilidad acerca de variables continuas aleatorias esta dado por:</p>
<p><span class="math inline">\(z=\frac{x-\mu}{\sigma}\)</span></p>
<p>A menudo sucede que desconocemos los valores de la media. y de desviación típica. Es por lo que utilizamos los estadísticos de una muestra dados por el promedio y la desviación estándar (s) y se consideran buenos estimadores de la media y la varianza</p>
<p><span class="math inline">\(z=\frac{\overline{x} - \mu}{\sigma}\)</span></p>
<p>Estandarizando una observación <span class="math inline">\(\overline{x}\)</span> a su valor z, podemos relacionarlo con las propiedades de las curvas normales.</p>
<p>Ejemplo 6.3.</p>
<p>Un estudio acerca de la estructura de árboles, determino que la población de la especie de Cecropias en la zona del Caribe tienen una media en DAP cercana a los 63 cm con una desviación estándar de 4.4 cm. Se quisiera determinar otras mediaciones en una zona próxima y suponiendo que los datos pertenecen a una población grande con una distribución aproximadamente normal.</p>
<ol style="list-style-type: lower-alpha">
<li>Es posible encontrar arboles con DAP igual a 60 cm que pertenezcan a esa misma población?</li>
</ol>
<div id="section-solución." class="section level4">
<h4>Solución.</h4>
<pre><code>## 
##  One Sample z-test
## 
## data:  60
## z = -0.68182, n = 1.0, Std. Dev. = 4.4, Std. Dev. of the sample mean =
## 4.4, p-value = 0.4954
## alternative hypothesis: true mean is not equal to 63
## 95 percent confidence interval:
##  51.37616 68.62384
## sample estimates:
## mean of 60 
##         60</code></pre>
<p>o</p>
<pre><code>## [1] 0.4953539</code></pre>
<p><span style="color:red">Nota:</span> Entender que la pregunta es en masa y la función dnorm no calcula en masa, calcula la densidad, es por ello por lo que para convertir la respuesta a una función en masa la multiplicamos por dos, de esta manera tendremos la solución. Esto opción solo aplica cuando la pregunta es menor a la media, en este caso la pregunta era a 60 y nuestra media es mayor “63”</p>
<p><span style="color:red">Nota 2:</span> Cuando la pregunta en masa, tiene un valor que supera la media se debe aplicar <span style="color:blue"> (1-pnorm(x))*2</span>. Ejemplo:</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Es posible encontrar arboles con DAP igual a 67 cm que pertenezcan a esa misma población?</li>
</ol>
<pre><code>## [1] 0.3633021</code></pre>
<p>Mismo resultado que obtenemos con z.test</p>
<pre><code>## 
##  One Sample z-test
## 
## data:  67
## z = 0.90909, n = 1.0, Std. Dev. = 4.4, Std. Dev. of the sample mean =
## 4.4, p-value = 0.3633
## alternative hypothesis: true mean is not equal to 63
## 95 percent confidence interval:
##  58.37616 75.62384
## sample estimates:
## mean of 67 
##         67</code></pre>
<p>Observe que esta aplicación “TeachingDeamos” nos brinda el resultado de z = -0.6818, y la probabilidad de que el evento ocurra: p-value = 0.4954. Así mismo nos calcula el intervalo de confianza = [51.37 a 68.62].</p>
<p>La función “pnorm” únicamente nos permite calcular la probabilidad. Esta es reducida en cuanto a la información brindada, no permite calcular un nivel de significación diferente al 95% como si lo hace “z.test”, pero es suficiente para responder lo que nos interesa.</p>
<p>Las áreas de rechazo al 95% de confianza en la curva normal estándar están determinadas por 1.96 desviaciones estándar a cada lado</p>
<p>Figura. 5. Curva normal estándar, al 95 % de confianza mostrando sus áreas de aceptación de la</p>
<p>Como observa el valor de z (-0.68) cae dentro del área de aceptación de más menos 1.96 desviaciones estándar.</p>
<p>R/ Se puede determinar que arboles con DAP igual a 60 cm pertenecen a esa población con una confiabilidad del 95%.</p>
<p>Con base al área de rechazo de z=-0.68, podríamos concluir, además, si se nos hubiese planteado la hipótesis que:</p>
<p>H0= DAP =60 H1= DAP dif 60.</p>
<p>Si se planteara la pregunta:</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Determine la probabilidad de encontrar arboles con DAP mayores a 70 cm, dentro de la población</li>
</ol>
<p>H0= DAP menor o igual 70 H1= DAP &gt; 70</p>
<p>Note que ahora estamos interesados en conocer la probabilidad de un evento dado.</p>
<p>Solución:</p>
<pre><code>## 
##  One Sample z-test
## 
## data:  70
## z = 1.5909, n = 1.0, Std. Dev. = 4.4, Std. Dev. of the sample mean =
## 4.4, p-value = 0.05582
## alternative hypothesis: true mean is greater than 63
## 95 percent confidence interval:
##  62.76264      Inf
## sample estimates:
## mean of 70 
##         70</code></pre>
<p>o</p>
<pre><code>## [1] 0.05581502</code></pre>
<p>Calculando el valor de z</p>
<pre><code>## [1] 1.590909</code></pre>
<p>Note que la función “qnorm” nos permite calcular el valor de z estandarizado de los datos. Esto únicamente funciona para funciones acumuladas. Siempre debe utilizar lower.tail = FALSE, para que dé el verdadero valor de z, sino el valor podría tener un símbolo diferente.</p>
<p>Compare sus resultados utilizando “TeachingDemos” y “pnorm”. Deben de coincidir.</p>
<p>Nota: Verifique también el uso de la tabla de normal estándar para contrastar su respuesta.</p>
<p>También podemos hacer uso directo definiendo la hipótesis alternativa en el comando de z.test.</p>
<p>R/ la probabilidad de encontrar arboles con DAP mayores a 70 es de un 5%.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Probabilidad de encontrar arboles mayores a 55 cm.</li>
</ol>
<pre><code>## 
##  One Sample z-test
## 
## data:  55
## z = -1.8182, n = 1.0, Std. Dev. = 4.4, Std. Dev. of the sample mean =
## 4.4, p-value = 0.9655
## alternative hypothesis: true mean is greater than 63
## 95 percent confidence interval:
##  47.76264      Inf
## sample estimates:
## mean of 55 
##         55</code></pre>
<div id="section-o" class="section level5">
<h5>o</h5>
<pre><code>## [1] 0.9654832</code></pre>
<p>R/ la probabilidad de encontrar arboles mayores a 55 cm es de un 96%.</p>
<p>Ejemplo 6.4.</p>
<p>Se realiza un estudio para conocer los ámbitos de acción de especies de perezosos durante un periodo de un mes, se seleccionan de manera aleatoria de la población 35 individuos. Los datos fueron registrados en hectáreas por mes.</p>
<pre><code>##  [1]  8.08  6.33  7.88 10.98  7.81  6.49  9.67  9.17  9.06  9.77  8.89  6.06
## [13]  7.86  6.86 11.79  4.88 10.42  4.98  6.25  7.04  7.76  5.33  4.98  7.00
## [25]  8.74  7.14  6.73  7.79  9.48  8.86  6.29  9.73  9.00  5.39  7.56</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Cual es la probabilidad de encontrar un individuo dentro de la población cuyo ámbito de acción sea igual a 7.5?</li>
</ol>
<pre><code>## [1] 7.772857</code></pre>
<pre><code>## [1] 1.771116</code></pre>
<p>Solución:</p>
<pre><code>## 
##  One Sample z-test
## 
## data:  7.5
## z = -0.11299, n = 1.00, Std. Dev. = 1.77, Std. Dev. of the sample mean
## = 1.77, p-value = 0.91
## alternative hypothesis: true mean is not equal to 7.7
## 95 percent confidence interval:
##   4.030864 10.969136
## sample estimates:
## mean of 7.5 
##         7.5</code></pre>
<p>o</p>
<pre><code>## [1] 0.8775628</code></pre>
<p>R/ Tengo una probabilidad del 87.75% de encontrar un individuo cuyo radio de acción sea de 7.5 ha al 95% de confianza.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Cuál es la probabilidad de encontrar individuos cuyo ámbito de acción este entre 5.8 y 7.8 hectáreas al 95% de confianza?</p></li>
<li><p>Pr(x&gt;7)?</p></li>
<li><p>Pr(x menor o igual a 5.8)?</p></li>
<li><p>Pr(x mayor o igual a 6.5)?</p></li>
</ol>
<p>Material elaborado por: Oscar Ramírez Alan (QDGG)</p>
<p>Modificado por: Meyer Guevara Mora</p>
<p>Versión: 2020-08-14 15:21:03</p>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
library(lubridate)
library(vegan)
library(ade4)
library(fdth)
library(MASS)
library(PerformanceAnalytics)
library(TeachingDemos)
library(tidyverse)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-explorar_codigo-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-explorar_codigo-code-editor`)), session)
output$`tutorial-exercise-explorar_codigo-output` <- renderUI({
  `tutorial-exercise-explorar_codigo-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94]}},"value":[{"type":"character","attributes":{},"value":["ade4","assertthat","backports","base","blob","broom","cellranger","cli","cluster","colorspace","compiler","crayon","datasets","DBI","dbplyr","digest","dplyr","ellipsis","evaluate","fansi","fastmap","fdth","forcats","fs","generics","ggplot2","glue","graphics","grDevices","grid","gtable","haven","hms","htmltools","htmlwidgets","httpuv","httr","jsonlite","knitr","later","lattice","learnr","lifecycle","lubridate","magrittr","markdown","MASS","Matrix","methods","mgcv","mime","modelr","munsell","nlme","parallel","PerformanceAnalytics","permute","pillar","pkgconfig","promises","purrr","quadprog","R6","Rcpp","readr","readxl","reprex","rlang","rmarkdown","rprojroot","rstudioapi","rvest","scales","shiny","splines","stats","stringi","stringr","TeachingDemos","tibble","tidyr","tidyselect","tidyverse","tools","utils","vctrs","vegan","withr","xfun","xml2","xtable","xts","yaml","zoo"]},{"type":"character","attributes":{},"value":["1.7-15","0.2.1","1.1.8","4.0.2","1.2.1","0.7.0","1.1.0","2.0.2","2.1.0","1.4-1","4.0.2","1.3.4","4.0.2","1.1.0","1.4.4","0.6.25","1.0.1","0.3.1","0.14","0.4.1","1.0.1","1.2-5","0.5.0","1.5.0","0.0.2","3.3.2","1.4.1","4.0.2","4.0.2","4.0.2","0.3.0","2.3.1","0.5.3","0.5.0","1.5.1","1.5.4","1.4.2","1.7.0","1.29","1.1.0.1","0.20-41","0.10.1","0.2.0","1.7.9","1.5","1.1","7.3-51.6","1.2-18","4.0.2","1.8-31","0.9","0.1.8","0.5.0","3.1-148","4.0.2","2.0.4","0.9-5","1.4.6","2.0.3","1.1.1","0.3.4","1.5-8","2.4.1","1.0.5","1.3.1","1.3.1","0.3.0","0.4.7","2.3","1.3-2","0.11","0.3.6","1.1.1","1.5.0","4.0.2","4.0.2","1.4.6","1.4.0","2.12","3.0.3","1.1.1","1.1.0","1.3.0","4.0.2","4.0.2","0.3.2","2.5-6","2.2.0","0.16","1.3.2","1.8-4","0.12-0","2.2.1","1.8-8"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">02_Distribución_continua</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
